Ot135 128 grupo datos g
alkemyTech/OT135-Proyecto-2 pull request #2
Opened 2022-02-15 17:10 UTC by Ldavidts

2022-02-17 02:38 UTC, julianpalmerio requested changes
El código en general esta bien, la parte mas compleja que es la de poder utilizar el archivo cfg o ini para configurar el log esta bien lograda. Te dejo algunos comentarios para poder aprobarlo!

2022-02-17 02:38 UTC, julianpalmerio commented on Grupo-Datos-G/logging.ini
> +datefmt=%Y-%m-%d
No es el formato de fecha solicitado en la tarea.

2022-02-17 02:38 UTC, julianpalmerio commented on Grupo-Datos-G/logging.ini
> +datefmt=%Y-%m-%d
No es el formato de fecha solicitado en la tarea.

2022-02-17 02:38 UTC, julianpalmerio commented on Grupo-Datos-G/main.py
> +logger = logging.getLogger('__name__')
Aqui deberias usar la variable __name__ por lo que no van las comillas.

2022-02-17 02:38 UTC, julianpalmerio commented on Grupo-Datos-G/main.py
> +logger.error('This is error')
Esta bien para probar el funcionamiento, pero no estaba solicitado en la tarea hacer logs!. Solo configurar el logger!

2022-02-17 03:17 UTC, Ldavidts commented on Grupo-Datos-G/logging.ini
> +datefmt=%Y-%m-%d
> El código en general esta bien, la parte mas compleja que es la de poder utilizar el archivo cfg o ini para configurar el log esta bien lograda. Te dejo algunos comentarios para poder aprobarlo!

Gracias Julian, no sabía que el formato de fecha %A-%B traía el dia y el mes en letras, buenísimo que se aprende algo todos los días y yo que no quería probar no fuese a romper el código. Listo corregí los detalles y envié el Push

2022-02-18 04:19 UTC, julianpalmerio commented on Grupo-Datos-G/logging.ini
> +datefmt=%Y-%m-%d
Buenísimo entonces, es la idea, aprender!

2022-02-18 04:19 UTC, julianpalmerio commented on Grupo-Datos-G/main.py
> +from logging import config
Ojo con este import que esta sin uso.

2022-02-18 04:19 UTC, julianpalmerio approved these changes
Te deje un comentario mas, pero ya esta todo bien, lo apruebo!

2022-02-18 04:19 UTC, merged