Ot135-126-grupo-datos-e
alkemyTech/OT135-Proyecto-2 pull request #3
Opened 2022-02-16 00:09 UTC by aguyanzon

# Configuración de logs para grupo de datos E
* Se crea un entorno virtual.
* Se crea un archivo **.ini** con las configuraciones correspondientes al log .
* Se crea un archivo **main.py** que lee el archivo **.ini** y ejecuta los logs en consola y en un fichero **.log**.

[Link a la tarea](https://alkemy-labs.atlassian.net/jira/software/c/projects/OT135/boards/208?modal=detail&selectedIssue=OT135-126&assignee=61eea96725edab006af93e59 )

2022-02-17 02:45 UTC, julianpalmerio requested changes
El código esta muy bien, la parte de configurar el log desde el ini esta perfecta, pero hay detalles que no coinciden con los solicitados en la tarea!

2022-02-17 02:45 UTC, julianpalmerio commented on Grupo-Datos-E/logging.ini
> +datefmt=%Y-%m-%d
El format y el datefmt no son los que se solicitaron en la tarea!

2022-02-17 02:45 UTC, julianpalmerio commented on Grupo-Datos-E/main.py
> +logger = logging.getLogger('Grupo-E')
Por lo que veo en la tarea podrias usar la variable __name__

2022-02-17 12:18 UTC, aguyanzon commented on Grupo-Datos-E/logging.ini
> +datefmt=%Y-%m-%d
No me di cuenta Julian! Ahí lo acabo de pushear. Gracias!

2022-02-18 04:23 UTC, julianpalmerio approved these changes

2022-02-18 04:23 UTC, merged